### ISSUE TITLE
Abbility to update the config prior loading the users / groups

### ISSUE THREAD

**Issue by DidouJazz** [bitnami/bitnami-docker-openldap#67]
**Description**

I need to have the memberOf overlay enabled for my project.
First, I was not able to use the LDAP_CUSTOM_LDIF_DIR as this does not use the ADMIN_CONFIG but the ADMIN user.
Second, adding a .sh file under the docker-entrypoint.d to add the overlay is applied after the bootstrap of the users / groups. 
=> the memberOf overlay is not applied to existing groups.

I was able to solve this overwriting the libopenldap.sh but this is dangerous especially if you'll change this file in futur.

Is there an option to run ldifs (using the ADMIN_CONFIG user) prior the execution of the ldifs in LDAP_CUSTOM_LDIF_DIR ?

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Using AKS on Azure

**Comment by juan131** [comment]
Hi @DidouJazz 

This container supports loading custom scripts so you can customize your LDAP configuration. That said, theses scripts will be executed after LDAP initialization based on env. variables, see:

- https://github.com/bitnami/bitnami-docker-openldap#initializing-a-new-instance

You could try setting the env. variable `LDAP_SKIP_DEFAULT_TREE=true` to skip the skip creating the default LDAP tree and then, use custom scripts to create the desired tree.

**Comment by DidouJazz** [comment]
Hi @juan131 ,

I made it based on your advice, here is the content of my 01-memberOf.sh (mounted under the /docker-entrypoint-initdb.d folder).

```bash
#!/bin/bash
#
# Bitnami OpenLDAP library

# shellcheck disable=SC1090,SC1091

# Load Generic Libraries
. /opt/bitnami/scripts/libopenldap.sh

########################
# Configure LDAP memberOf overlay
# Globals:
#   LDAP_*
# Arguments:
#   None
# Returns:
#   None
#########################
ldap_memberof_overlay() {
	info "Configure LDAP memberOf overlay"

	cat >> "${LDAP_SHARE_DIR}/memberOf.ldif" << EOF
# Overlay for memberOf
dn: cn=module,cn=config
changetype: add
cn: module
objectClass: olcModuleList
objectClass: top
olcModuleLoad: memberof

dn: olcOverlay={0}memberof,olcDatabase={2}mdb,cn=config
changetype: add
objectClass: olcConfig
objectClass: olcMemberOf
objectClass: olcOverlayConfig
objectClass: top
olcOverlay: memberof
olcMemberOfDangling: ignore
olcMemberOfRefInt: TRUE
olcMemberOfGroupOC: groupofUniqueNames
olcMemberOfMemberAD: uniqueMember

dn: cn=module,cn=config
changetype: add
cn: module
objectclass: olcModuleList
objectclass: top
olcmoduleload: refint

dn: olcOverlay={1}refint,olcDatabase={2}mdb,cn=config
changetype: add
objectClass: olcConfig
objectClass: olcOverlayConfig
objectClass: olcRefintConfig
objectClass: top
olcOverlay: {1}refint
olcRefintAttribute: memberof member owner
EOF
	debug_execute ldapmodify -Y EXTERNAL -H "ldapi:///" -f "${LDAP_SHARE_DIR}/memberOf.ldif"
}

ldap_start_bg
ldap_memberof_overlay
ldap_add_schemas
ldap_add_custom_ldifs
ldap_stop
```

From my point of view, this is solved.
Thx

**Comment by BLKFSH** [comment]
@DidouJazz Your script seems to finally enable the memberOf overlay for me, but any user I add/assign a group to still doesn't seem to have the attribute. Do I need to specify a custom schema or something for my users to add the attribute?
